name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.4'
        bundler: '2.3.26'
    
    - name: Install dependencies
      run: |
        gem install bundler -v '2.3.26'
        bundle config set --local path 'vendor/bundle'
        bundle install --jobs 4 --retry 3
    
    - name: Build site
      run: bundle exec jekyll build
      env:
        JEKYLL_ENV: production
    
    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site 